"""
compute_similarity_measures.py
-------------------------------
Computes all five fuzzy similarity measures from Excel data files
(ideal vs IBM/noisy counts) and reproduces the paper's tables.

Place this script in the same folder as your Excel files, then run:
    python compute_similarity_measures.py

Expected files (generated by grover_ideal_correct.py and grover_ibm_hardware.py):
    grover_ideal_<state>.xlsx
    grover_IBM_<state>.xlsx

Requirements:
    pip install numpy openpyxl scipy pandas
"""

import os
import numpy as np
from scipy import stats
import openpyxl

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# ── Five Fuzzy Similarity Measures ────────────────────────────────────────

def hamming(a, b):
    """M1: Normalised Hamming similarity."""
    return 1 - np.sum(np.abs(a - b)) / len(a)

def euclidean(a, b):
    """M2: Normalised Euclidean similarity."""
    return 1 - np.sqrt(np.sum((a - b)**2)) / np.sqrt(len(a))

def cosine(a, b):
    """M3: Cosine similarity. Tracks distribution shape alignment."""
    denom = np.linalg.norm(a) * np.linalg.norm(b)
    return float(np.dot(a, b) / denom) if denom > 0 else 0.0

def hausdorff(a, b):
    """M4: Hausdorff similarity. Sensitive to worst-case single-state deviation."""
    return 1 - float(np.max(np.abs(a - b)))

def minkowski(a, b, p=2):
    """M5: Normalised Minkowski similarity (at p=2 this equals M2)."""
    return 1 - (np.sum(np.abs(a - b)**p) / len(a))**(1/p)

def compute_all(ideal_p, ibm_p):
    return (hamming(ideal_p, ibm_p), euclidean(ideal_p, ibm_p),
            cosine(ideal_p, ibm_p), hausdorff(ideal_p, ibm_p),
            minkowski(ideal_p, ibm_p))

# ── Data Loading ──────────────────────────────────────────────────────────

def load_run(filepath, run_number):
    """Load one run (column) from an Excel count file."""
    wb = openpyxl.load_workbook(filepath, read_only=True)
    ws = wb.active
    rows = list(ws.iter_rows(values_only=True))
    counts = {}
    for row in rows[1:]:
        state = row[0]
        if state is not None and row[run_number] is not None:
            counts[str(state)] = int(row[run_number])
    return counts

def to_prob_vector(counts, all_states):
    arr = np.array([counts.get(s, 0) for s in all_states], dtype=float)
    total = arr.sum()
    return arr / total if total > 0 else arr

# ── Analysis ──────────────────────────────────────────────────────────────

def analyse(n, marked_states, ideal_prefix="grover_ideal",
            ibm_prefix="grover_IBM", threshold=0.9):
    all_states = [format(i, f'0{n}b') for i in range(2**n)]
    all_measures = []

    print(f"\n{'='*65}")
    print(f"{n}-QUBIT GROVER'S: Ideal vs IBM Hardware")
    print(f"{'='*65}")
    print(f"{'Exec':>4} {'Marked':>7} {'M1':>8} {'M2':>8} {'M3':>8} {'M4':>8} {'M5':>8}")

    for i, marked in enumerate(marked_states):
        run_num = i + 1
        ideal_file = os.path.join(SCRIPT_DIR, f"{ideal_prefix}_{marked}.xlsx")
        ibm_file   = os.path.join(SCRIPT_DIR, f"{ibm_prefix}_{marked}.xlsx")

        if not os.path.exists(ideal_file):
            print(f"  Missing: {os.path.basename(ideal_file)}")
            continue
        if not os.path.exists(ibm_file):
            print(f"  Missing: {os.path.basename(ibm_file)}")
            continue

        ideal_c = load_run(ideal_file, run_num)
        ibm_c   = load_run(ibm_file,   run_num)
        ip = to_prob_vector(ideal_c, all_states)
        bp = to_prob_vector(ibm_c,   all_states)
        measures = compute_all(ip, bp)
        all_measures.append(measures)
        print(f"{run_num:>4} {marked:>7} " + " ".join(f"{m:>8.4f}" for m in measures))

    if not all_measures:
        print("No data loaded — check that Excel files are in the same folder as this script.")
        return

    r = np.array(all_measures)
    print(f"\n{'Mean':>12} " + " ".join(f"{r[:,j].mean():>8.4f}" for j in range(5)))
    print(f"{'SD':>12} "   + " ".join(f"{r[:,j].std():>8.4f}"  for j in range(5)))
    print(f"{'Min':>12} "  + " ".join(f"{r[:,j].min():>8.4f}"  for j in range(5)))
    print(f"{'Max':>12} "  + " ".join(f"{r[:,j].max():>8.4f}"  for j in range(5)))

    print(f"\nT-test against threshold {threshold}:")
    for j, name in enumerate(['M1','M2','M3','M4','M5']):
        t_stat, p_val = stats.ttest_1samp(r[:, j], threshold)
        above = int(np.sum(r[:, j] >= threshold))
        print(f"  {name}: t={t_stat:8.2f}  p={p_val:.4f}  above_{threshold}={above}/{len(r)}")

# ── Run ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    marked_3 = ['000','001','010','011','100','101','110','111','000','001']
    analyse(3, marked_3)

    marked_4 = ['0000','0001','0010','0011','0100',
                '0101','0110','0111','1000','1001']
    analyse(4, marked_4)

    marked_5 = ['11100','00111','00111','11100','00111',
                '11100','00111','11100','00111','11100']
    analyse(5, marked_5)
